<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.1.0" />
  </ItemGroup>
  <ItemGroup>
    <None Update=".env" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Views\Forms\MainForm.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Views\Forms\MainForm.Designer.cs">
      <DependentUpon>MainForm.cs</DependentUpon>
    </Compile>
    <Compile Update="Views\Forms\ClienteEditForm.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Views\Forms\ClienteEditForm.Designer.cs">
      <DependentUpon>ClienteEditForm.cs</DependentUpon>
    </Compile>
  </ItemGroup>
</Project>
